name: scrape tweets

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/3 * * * *'

jobs:
  scrape_datagouvfr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.52.6
      - name: scrape @deliveroo_FR tweets
        shell: bash
        run: |
          #minet tw scrape tweets "from:@deliveroo_FR" --limit 10000 > deliveroo_FR-tweets.csv
          minet tw scrape tweets "@deliveroo_FR" --limit 10000 > deliveroo_FR-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: ğŸ¦ @deliveroo_FR
